### PR TITLE
Add Examples using a example.rst

### PR DESCRIPTION
**Pull request by Schamnad**
Have added examples for the ccget script using an Gaussian09 output file. The input used has been provided, the output was too large to paste and has not been provided at the moment.

The files I added were the examples.rst and edited the contents.rst to contain the example tag. All other files were modified when I ran the make command. 

Testing done: Opened and checked individual HTML files to see if any of the pages are broken on Chrome

To Do: Add examples where the scripts have been used in larger python scripts.

### CODE REVIEW

**Comment by Schamnad** [comment]
Have updated the pull request with a new commit containing ccwrite examples and editing a few naming mistakes in the previous commit.

**Comment by langner** [comment]
Looks good. I updated master about a week ago - could you please sync with it? You might be able to do this effortlessly by rebasing:
`git rebase upstream/master`
(replace "origin" with whateverthe  cclib upstream remote is called in your local repository.

**Comment by ATenderholt** [comment]
Note that since you've already pushed your code, I think a merge is more
appropriate than a rebase.
https://www.atlassian.com/git/tutorials/merging-vs-rebasing/

**Comment by Schamnad** [comment]
I'm not sure whether I'm doing this right or not. I have two local branches i.e Master and newExamples. newExamples has both my commits.
I followed these steps but it didn't show me the latest commits.
1) git checkout 'master'  (parent is 'origin/master')
2) git pull
3) Already up-to-date.
4) git checkout 'newExamples'  (parent is 'origin/newExamples')
5) git merge master
6) Already up-to-date.

git log shows me that the last commit made was:
```
Author: Karol M. Langner <karol.langner@gmail.com>
Date:   Mon May 25 11:11:50 2015 -0400

    Development: fix typo
```
It doesn't show the 2 commits which have taken place [after ](https://github.com/cclib/cclib.github.io/commits/master)

**Comment by langner** [comment]
> Note that since you've already pushed your code, I think a merge is more
> appropriate than a rebase.
> https://www.atlassian.com/git/tutorials/merging-vs-rebasing/

Rebasing should be fine, it'll rewrite the new commits (Sanjeed's in this case) on top of the ones from cclib/master.

**Comment by langner** [comment]
> I'm not sure whether I'm doing this right or not. I have two local branches i.e Master and newExamples. newExamples has both my commits.
> I followed these steps but it didn't show me the latest commits.
> 1) git checkout 'master' (parent is 'origin/master')
> 2) git pull
> 3) Already up-to-date.
> 4) git checkout 'newExamples' (parent is 'origin/newExamples')
> 5) git merge master
> 6) Already up-to-date.
> 
> git log shows me that the last commit made was:
> 
> Author: Karol M. Langner <karol.langner@gmail.com>
> Date:   Mon May 25 11:11:50 2015 -0400
> 
>     Development: fix typo
> It doesn't show the 2 commits which have taken place after

You need to rebase off of cclib's master. You need to have a remote set up. For example, here are my remotes:
```shell
$ git remote -v 
cclib   git@github.com:cclib/cclib.github.io.git (fetch)
cclib   git@github.com:cclib/cclib.github.io.git (push)
langner git@github.com:langner/cclib.github.io.git (fetch)
langner git@github.com:langner/cclib.github.io.git (push)
sanjeed https://github.com/Schamnad/cclib.github.io.git (fetch)
sanjeed https://github.com/Schamnad/cclib.github.io.git (push)
```

You might have `original` or `upstream` instead of `cclib`. If not, you can add it like so:
`git remote add cclib git@github.com:cclib/cclib.github.io.git`

When you have the upstream remote (I'll call it `cclib` here), you can them rebase:
```shell
git checkout newExamples
get fetch --all
git rebase cclib/master
```

Hope that helps!

**Comment by Schamnad** [comment]
Hello langner,
The git remote add command helped solve my problem. 
I followed the rest of the steps and performed the git rebase command. The command didn't complete as there were conflicts in quite a few of the auto-generated files (~20 files). I tried resolving the conflicts in a few files, then I realized I didn't have the requisite knowledge to complete it for all files, for eg. there is a conflict in the searchindex.js file.
Given the fact that the examples page depends on a completely new examples.rst and a simple edit to the contents.rst page, would it be okay if I made a new branch with the latest master and then "make" the examples page on top of this? This shall eliminate all the conflicts because of having an outdated master branch.

**Comment by langner** [comment]
> Hello langner,
> The git remote add command helped solve my problem. 
> I followed the rest of the steps and performed the git rebase command. The command didn't complete as there were conflicts in quite a few of the auto-generated files (~20 files). I tried resolving the conflicts in a few files, then I realized I didn't have the requisite knowledge to complete it for all files, for eg. there is a conflict in the searchindex.js file.
> Given the fact that the examples page depends on a completely new examples.rst and a simple edit to the contents.rst page, would it be okay if I made a new branch with the latest master and then "make" the examples page on top of this? This shall eliminate all the conflicts because of having an outdated master branch.

Yup, that's definitely the way to do it if there are conflicts. Don't bother merging automatically generated files manually!

**Comment by Schamnad** [comment]
I have created a new Pull request for the feature. This feature was created on top of the latest master changes.
New Pull Request : #17 
I shall be closing this pull request.

**Pull request closed without merging**
